name: Run prettier

on:
  push:
  pull_request:
    branches:
    - master

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Make sh executable
      run: chmod +x ./.github/workflows/lint.sh

    - name: Run lint
      run: ./.github/workflows/lint.sh